### ISSUE TITLE
about the ozone units?

### ISSUE THREAD

**Issue by maurosc3ner** [degauss-org/degauss_schwartz_guide#2]
I have used this package successfully, but I want to double check that ozone units returned are correct (PPM).

A division by 1000 is required to meet EPA thresholds (guidelines->https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf).

Thanks

**Comment by cole-brokamp** [comment]
Hi Esteban, I think that the units are correct.  We are using estimates very similar to what is hosted here: https://sedac.ciesin.columbia.edu/data/set/aqdh-o3-concentrations-contiguous-us-1-km-2000-2016 and are derived from the same statistical model and associated manuscript.  I'm unfamiliar with the model specifics.
